### ISSUE TITLE
Need a better readme

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/mbed-drivers#105]
The readme doesn't describe anything about what this module actually is / does, and doesn't provide any links to further resources.

**Comment by 0xc0170** [comment]
drivers/hal/cmsis require adding readme. I should probably add an issue to each of those, to start fixing

**Comment by autopulated** [comment]
ack. [enhancement]s won't get pulled into jira, so maybe this shouldn't be tagged like that?

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTSFW-1067

**Comment by bogdanm** [comment]
Would you say #109 fixed this?

**Comment by autopulated** [comment]
yup

**Comment by bogdanm** [comment]
Fixed by #109.
