### ISSUE TITLE
Readme - should contain information stability of this module

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/mbed-drivers#153]
It might be beneficial to add more information to our Readme here, to explain why it's 0.x.x, to provide an example how to use this module as dependency.

@bogdanm @autopulated @bremoran @mjs-arm

**Comment by yogpan01** [comment]
Please also add recommended usage of this module to the developers. Dos and Donts and potential risks of what happens if they accidently do it the wrong way.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2088

**Comment by 0xc0170** [comment]
There was a release of 1.0.0 of mbed drivers, which added a readme section aobut the future of mbed-drivers. This should fix this issue.
