### ISSUE TITLE
Release process when changing dependency versions

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-drivers#172]
There was a recent issue with the core-util module having a circular dependency on an older version of mbed-drivers. This lead to broken examples during a hackathon and workshop that was given over the weekend.

These dependency problems can be easily avoided in the future by having basic CI checks. Are these tests currently in place? If so, how come the change it made it through?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2218

**Comment by 0xc0170** [comment]
@PrzemekWirkus

**Comment by bridadan** [comment]
Anybody?

As an experiment, I made a Travis CI config that will build all the tests whenever a PR/commit is made. Do we need something like this? Or is this being handled internally?

Link to the experiment: https://github.com/bridadan/mbed-drivers/pull/1

**Comment by 0xc0170** [comment]
@bridadan +1 to have the travis running automatically.

**Comment by bridadan** [comment]
Closing this, let's continue any discussion on the PR #180
