### ISSUE TITLE
add config option to disable retargeting

### ISSUE THREAD

**Issue by bearsh** [ARMmbed/mbed-drivers#174]
retarget always init the serial port as soon as `DEVICE_SERIAL` is set. to me that's a strange assumption. only because the hardware has a serial port does not mean one is going to use in such a way.
my suggestion is to add a `yotta` config option to disable retargeting even if the hardware defines `DEVICE_SERIAL`.

**Comment by 0xc0170** [comment]
> retarget always init the serial port as soon as DEVICE_SERIAL is set.

If you don't use any stdio in your app (printf(), etc), it should not be initialized. code reference: https://github.com/ARMmbed/mbed-drivers/blob/master/source/retarget.cpp#L177

**Comment by bearsh** [comment]
sorry you're right I missed that part. hopefully the compiler is smart enough to optimize away the unused code...

talking about retargeting, what do you think about to integrate the Segger RTT as another possible 'backend', maybe selectable by a yotta config option? (of course this would need a new ticket)

**Comment by 0xc0170** [comment]
> talking about retargeting, what do you think about to integrate the Segger RTT as another possible 'backend', maybe selectable by a yotta config option? (of course this would need a new ticket)

I am not fully familiar with the implementation, you can open a new ticket for this. If you make it work, let us know.

I am closing this issue.

**Comment by Arjun765** [comment]
>If you don't use any stdio in your app (printf(), etc), it should not be initialized. code reference: https://github.com/ARMmbed/mbed-drivers/blob/master/source/retarget.cpp#L177

it seems `fault_print_init()` in `mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.c` initializes serial and uses it for printing.

**Comment by 0xc0170** [comment]
@guest253456 This issue is for older codebase that had a bit different retarget (see it points to mbed-drivers repo). 

If there is an issue now , even if it is similar, please file a new issue
