### ISSUE TITLE
serial_tx_active() in SerialBase::set_dma_usage_rx()

### ISSUE THREAD

**Issue by dbaba** [ARMmbed/mbed-drivers#184]
Occasionally I found the following code:
https://github.com/ARMmbed/mbed-drivers/blob/master/source%2FSerialBase.cpp#L157

Is it correct?
I'd say `serial_rx_active()` should be placed there.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2424

**Comment by 0xc0170** [comment]
@dbaba yes, should be corrected, thanks for reporting
