### ISSUE TITLE
AnalogIn : Need a new function to return the ADC raw data

### ISSUE THREAD

**Issue by bcostm** [ARMmbed/mbed-drivers#186]
Today the ADC data is scaled to 16bits. It is necessary in some applications to return the ADC raw data. A new function can be added to the AnalogIn api:
For example:
   unsigned short read_raw() { 
        return analogin_read_raw(&_adc); 
    }

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2450

**Comment by markus-becker-tridonic-com** [comment]
This would be highly useful, for e.g. CPU internal temperature 12-bit ADCs, where datasheets give you conversion formulas, that assume 12-bit non-scaled raw values as input.

**Comment by markus-becker-tridonic-com** [comment]
> Yes, it returns a float and then we'll have to multiply by 0xFFF and convert to a uint16_t... This is why I asked if this method was ok for you...

@mlnx @bcostm I don't think it is a good idea to go this way if the solution is so easy: adc_read should be part of the API.

The workaround involves float calculations which are completely unnecessary and might introduce additional problems.

**Comment by mlnx** [comment]
@0xc0170 please review this

**Comment by 0xc0170** [comment]
It sound sensible.

It should probably return unsigned int value (there are ADC on some chips -  for instance sigma delta with 24bit).

**Comment by mlnx** [comment]
Update: under internal discussion at ARM mbed.

**Comment by anpilog** [comment]
Hi guys,
Any decision so far?

**Comment by mlnx** [comment]
This is unlikely to be fixed soon.

**Comment by markus-becker-tridonic-com** [comment]
Is it because it's non-sense, or because its going to be deprecated soon? If neither, this should be kept open, so that it still can be tracked, or?
