### ISSUE TITLE
Mbed-cli and Windows serial driver does not finish installation for many dev boards (critical bug) (updated)

### ISSUE THREAD

**Issue by Navis-Raven** [ARMmbed/mbed-drivers#194]
All of the bug is described here:
https://github.com/ARMmbed/mbed-cli/issues/733

Screenshot
![image](https://user-images.githubusercontent.com/15887222/44788474-70c3e600-ab9a-11e8-9373-83ccbb0bf30b.png)

Last conclusion: The problem is not a problem of a particular OS (same problem is in windows 7 as well as on windows 8.1), nor a problem of dev board (same problem on both of nRF52-DK and B-L475E-IOT01A), it's a more general problem and critical bug !

**Comment by 0xc0170** [comment]
Not related to this repository, cli is the correct one to report this one. I'll close this

**Comment by Navis-Raven** [comment]
@0xc0170  Ok so the problem is from cli ? but I had the same problem with "Windows serial driver" downloadable here: https://os.mbed.com/docs/latest/tutorials/windows-serial-driver.html

**Comment by 0xc0170** [comment]
this repository is not for this type of the problem. The name might confuse you as its mbed-drivers. This type of problem is better to report to cli repository or ask on Mbed forums (our support will pick this up from there).

**Comment by Navis-Raven** [comment]
Ok
