### ISSUE TITLE
How can i implement htrun (Key-value) protocol without using greentea or greentea client, or mbed-ls?

### ISSUE THREAD

**Issue by mukundsharma15** [ARMmbed/mbed-drivers#195]
I am following this GitHub link for htrun -- https://github.com/ARMmbed/htrun  
But what I want to do is to implement Htrun on host side, The DUT side will be taken care of, Is there any way to use the functionality of HTRUN on host and exchanges key-value messages between DUT and host.

The above resource explains the interaction between greentea client and htrun, I didn't find any specific example for fully implement htrun and exchange key;values

What i tried is mbedhtrun to flash and reset, after that?? how can I send data serially and get response, not able to find specific resource for this.

I am new to this mbed and htrun please share some useful resources.

what I tried looks like:

-- mbedhtrun -d D: -p /dev/ttyUSB0:115200
-- {{__sync;5f8dbbd2-199a-449c-b286-343a57da7a37}}

after this how can I use those setup(), and callback methods?
how can i use serial Tx and Rx to communicate from raspberry pi to DUT?

I am not able to completely understand greentea and htrun, a good example will be appreciated..
Thanks in advance

@ARMmbed 
@bridadan

**Comment by 0xc0170** [comment]
Hi, please create an issue to the tools repo rather than here : https://github.com/ARMmbed/mbed-os-tools

I'll close this as "won't fix here"
