### ISSUE TITLE
Test config & naming

### ISSUE THREAD

**Issue by sg-** [ARMmbed/mbed-drivers#75]
Test config should not be defined in the tests, rather, pushed to the targets.

Test naming needs change to be more representative of what they do or have a better mechanism of knowing how they match the test runners.

https://github.com/ARMmbed/mbed-drivers/pull/67

**Comment by 0xc0170** [comment]
What about the naming for those tests pins?

Let's start with hw pins for testing. In yotta target, something like

```
  "config": {
    "test": {
        "spi": {
            mosi: "pin1",
            miso: "pin2",
            sclk: "pin3",
            ssel: "pin4"
        },
        "i2c": {
            "sda": "pin5",
            "scl": "pin6"
        }
  }
```

**Comment by sg-** [comment]
that looks good! Need a document, maybe in greentea or in drivers (not sure which) that contains a living list of names that can be used to integrate with existing tests.

**Comment by autopulated** [comment]
you'll want to namespace the "test" stuff under either mbed-drivers, or some other prefix!

**Comment by 0xc0170** [comment]
Yes james I realized it should be under mbed-os or as mbed-drivers. That's something I was not certain about. The tests will be in mbed-hal/mbed-drivers, so I would go mbed-drivers then.

**Comment by bridadan** [comment]
I like it! +1 !

**Comment by bridadan** [comment]
I like it! +1 !

**Comment by 0xc0170** [comment]
Start of this effort - https://github.com/ARMmbed/target-frdm-k64f-gcc/pull/17

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-845

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1014

**Comment by 0xc0170** [comment]
This can be closed, the config test pins were defined for k64f and stm32f429.
